#!/bin/bash

#swaybg -i /home/cris/Pictures/a11.jpg
#swaybg -m fit -i /home/cris/Pics/macchiato.jpg;

exec-once = swaybg -o \* -i /home/cris/Pics/macchiato.jpg -m fill &

#rm -rf $HOME/.cache/swww &
#sleep 5;
#swww query || swww init && swww img /home/cris/Pics/NixOS.jpg;