#!/bin/bash
#swww img /usr/share/backgrounds/wallpapers-1/1.jpg
#swaybg -i /home/cris/Pictures/a11.jpg
swaybg -m fit -i $HOME/Pics/NixOS.jpg

#rm -rf $HOME/.cache/swww &
#sleep 5;
#swww query || swww init && swww img /home/cris/Pics/NixOS.jpg;